channels:
  - https://conda.anaconda.org/conda-forge
dependencies:
  - astroplan
  - fastapi
  - matplotlib-base
  - numpy
  - pandas
  - photutils
  - pip
  - scipy
  - streamz
  - uvicorn[standard]
  - pip:
      - panoptes-utils[config,images,social]==0.2.35
