---
parsers:
-
    type: GravWaveParse
    inputs:
        selection_criteria:
            name: 3_tiles
            max_tiles: 3
        fov:
            ra: 3.0
            dec: 2.0
        alert_pocs: True
        verbose: False
        save_file: False
        event: 'CBC' # Change to "Burst' to respond to unmodeled burst events.
