version: '3.7'
services:
  camera:
    image: huntsmanarray/huntsman-pocs-camera:develop
    privileged: true
    network_mode: host
    stdin_open: true
    tty: true
    environment:
      PANDIR: /var/huntsman
      PANOPTES_CONFIG_HOST:
      PANOPTES_CONFIG_PORT:
    deploy:
      resources:
        memory-swappiness: 1
        limits:
          memory: 704M
          memory-swap: 1G
        reservations:
          memory: 320M
    command: [ "huntsman-pyro --verbose service --service-class huntsman.pocs.camera.pyro.service.CameraService" ]
    volumes:
      - "${PANDIR}/images:/var/huntsman/images"
      - "${PANDIR}/logs:/var/huntsman/logs"
