version: '2.4'
services:
  camera:
    image: huntsmanarray/huntsman-pocs-camera:develop
    privileged: true
    network_mode: host
    stdin_open: true
    tty: true
    environment:
      PANDIR: /var/huntsman
      PANOPTES_CONFIG_HOST:
      PANOPTES_CONFIG_PORT:
    mem_limit: 704M
    memswap_limit: 1G
    mem_swappiness: 1
    mem_reservation: 320M
    command: [ "huntsman-pyro --verbose service --service-class huntsman.pocs.camera.pyro.service.CameraService" ]
    volumes:
      - "${PANDIR}/images:/var/huntsman/images"
      - "${PANDIR}/logs:/var/huntsman/logs"
