version: '3.7'

volumes:
  panlog:
    driver: local
    driver_opts:
      type: none
      device: ${PANDIR}/logs
      o: bind
  images:
    driver: local
    driver_opts:
      type: none
      device: ${PANDIR}/images
      o: bind
  config:
    driver: local
    driver_opts:
      type: none
      device: ${PANDIR}/huntsman-config/conf_files/pocs
      o: bind
  json_store:
    driver: local
    driver_opts:
      type: none
      device: ${PANDIR}/json_store
      o: bind
  archive:
    driver: local
    driver_opts:
      type: none
      device: ${PANDIR}/archive
      o: bind

services:
  pocs-config-server:
    image: huntsmanarray/huntsman-pocs:develop
    tty: true
    init: true
    container_name: pocs-config-server
    hostname: pocs-config-server
    deploy:
      mode: global
    network_mode: host
    environment:
      HUNTSMAN_POCS: /huntsman
      PANOPTES_CONFIG_HOST: 0.0.0.0
      PANOPTES_CONFIG_PORT: 6563
    restart: on-failure
    volumes:
      - config:/huntsman/conf_files
      - panlog:/huntsman/logs
      - images:/huntsman/images
    command: [ "panoptes-config-server --verbose run --no-save-local --no-load-local --config-file /huntsman/conf_files/huntsman.yaml" ]

  pyro-name-server:
    image: huntsmanarray/huntsman-pocs:develop
    tty: true
    init: true
    container_name: pyro-name-server
    hostname: pyro-name-server
    deploy:
      mode: global
    privileged: true
    network_mode: host
    restart: on-failure
    environment:
      HUNTSMAN_POCS: /huntsman
      PANOPTES_CONFIG_PORT: 6563
    command: [ "wait-for-it localhost:6563 -- huntsman-pyro nameserver --auto-clean 90" ]
    volumes:
      - config:/huntsman/conf_files
      - panlog:/huntsman/logs
      - images:/huntsman/images

  pocs-control:
    image: huntsmanarray/huntsman-pocs:develop
    tty: true
    init: true
    stdin_open: true
    container_name: pocs-control
    hostname: pocs-control
    deploy:
      mode: global
    privileged: true
    network_mode: host
    restart: on-failure
    environment:
      HUNTSMAN_POCS: /huntsman
      PANOPTES_CONFIG_PORT: 6563
    command: [ "wait-for-it localhost:6563 -- tail -f /dev/null" ]
    volumes:
      - config:/huntsman/conf_files
      - panlog:/huntsman/logs
      - images:/huntsman/images
      - json_store:/huntsman/json_store
      - archive:/huntsman/archive

  huntsman-file-archiver:
    image: huntsmanarray/huntsman-pocs:develop
    tty: true
    container_name: huntsman-file-archiver
    hostname: huntsman-file-archiver
    deploy:
      mode: global
    privileged: true
    network_mode: host
    restart: on-failure
    environment:
      HUNTSMAN_POCS: /huntsman
      PANOPTES_CONFIG_PORT: 6563
    command: [ "wait-for-it localhost:6563 -- /conda/bin/python /huntsman/scripts/archive-images.py" ]
    volumes:
      - config:/huntsman/conf_files
      - panlog:/huntsman/logs
      - images:/huntsman/images
      - archive:/huntsman/archive
