version: '3.3'

volumes:
  panlog:
    driver: local
    driver_opts:
      type: none
      device: ${PANDIR}/logs
      o: bind

services:

  pocs-config-server:
    image: huntsmanarray/huntsman-pocs:develop
    tty: true
    container_name: pocs-config-server
    hostname: pocs-config-server
    privileged: true
    network_mode: host
    environment:
      HUNTSMAN_POCS: /var/huntsman
      PANOPTES_CONFIG_HOST: 0.0.0.0
      PANOPTES_CONFIG_PORT: 6563
    restart: on-failure
    volumes:
      - "${PANOPTES_CONFIG_FILE}:/var/huntsman/huntsman-pocs/conf_files/huntsman.yaml"
    command: [ "panoptes-config-server --verbose run --config-file /var/huntsman/huntsman-pocs/conf_files/huntsman.yaml" ]
    volumes:
      - panlog:/var/huntsman/logs

  pyro-name-server:
    image: huntsmanarray/huntsman-pocs:develop
    tty: true
    container_name: pyro-name-server
    hostname: pyro-name-server
    privileged: true
    network_mode: host
    restart: on-failure
    depends_on:
      - "pocs-config-server"
    environment:
      HUNTSMAN_POCS: /var/huntsman
      PANDIR: /var/panoptes
      POCS: /var/panoptes/POCS
      PANOPTES_CONFIG_PORT: 6563
    command: [ "/var/panoptes/POCS/scripts/wait-for-it.sh localhost:6563 -- huntsman-pyro nameserver --auto-clean 90" ]
    volumes:
      - panlog:/var/huntsman/logs

  pyro-http:
    image: huntsmanarray/huntsman-pocs:develop
    tty: true
    container_name: pyro-http
    hostname: pyro-http
    privileged: true
    network_mode: host
    restart: on-failure
    depends_on:
      - "pyro-name-server"
    environment:
      HUNTSMAN_POCS: /var/huntsman
      PANDIR: /var/panoptes
      POCS: /var/panoptes/POCS
      PANOPTES_CONFIG_PORT: 6563
    command: [ "/var/panoptes/POCS/scripts/wait-for-it.sh localhost:6564 -- pyro5-httpgateway -p 8081 -e '.*'" ]
    volumes:
      - panlog:/var/huntsman/logs

  huntsman-control:
    image: huntsmanarray/huntsman-pocs:develop
    tty: true
    container_name: huntsman-control
    hostname: huntsman-control
    privileged: true
    network_mode: host
    restart: on-failure
    environment:
      HUNTSMAN_POCS: /var/huntsman
      PANDIR: /var/panoptes
      POCS: /var/panoptes/POCS
    command: /bin/bash
    volumes:
      - panlog:/var/huntsman/logs
