channels:
  - https://conda.anaconda.org/conda-forge
dependencies:
  - ipython # Interactive
  - matplotlib-base
  - numpy
  - photutils
  - pillow
  - pip
  - scipy
  - pip:
      - "git+https://github.com/panoptes/panoptes-utils.git@v0.2.35#egg=panoptes-utils[config,images,social]"
      - "git+https://github.com/panoptes/POCS.git@v0.7.8#egg=panoptes-pocs[focuser]" # Docker image uses updated github install
