channels:
  - https://conda.anaconda.org/conda-forge
dependencies:
  - astroplan
  - fastapi==0.116.*
  - matplotlib-base
  - numpy==1.26.*
  - pandas==2.3.*
  - photutils
  - pip
  - scipy==1.13.*
  - streamz
  - uvicorn[standard]
  - pip:
      - "git+https://github.com/panoptes/panoptes-utils.git#v0.2.35#egg=panoptes-utils[config,images,social]"
