version: '3.7'
services:
  testenv:
    image: huntsmanarray/testenv:latest
    user: huntsman
    privileged: true
    network_mode: host
    stdin_open: true
    tty: true
    init: true
    environment:
      HUNTSMAN_POCS: /var/huntsman
    volumes:
      - huntsmandir:/var/huntsman/huntsman-pocs
volumes:
  huntsmandir:
    driver: local
    driver_opts:
      type: none
      device: /var/huntsman
      o: bind
