on:
  push:
    branches: 
      - develop
      - huntsman_docker
  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file docker/huntsman_cameraserver.docker --tag test
